# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.13
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.206
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=dynamic_difficulty
mod_name=Dynamic Difficulty
mod_license=GPL v3
mod_version=0.9.0
mod_group_id=dev.muon.dynamic_difficuly
mod_authors=MuonR
mod_description=It's leveling time

# Publishing
curseforge_project=1272655

# Dev Env
jei_version=19.21.0.247
jade_version=15.1.6

# Integrations
apotheosis=8.4.0
apothic_enchanting=1.5.0
apothic_spawners=1.3.0
placebo=9.9.1
apothic_attributes=2.8.0

geckolib_version=1.21.1:4.7.5.1
irons_version=1.21.1-3.11.0
curios_version=9.5.1+1.21.1

player_animator=2.0.1+1.21.1
cloth_config=15.0.140

puffish_skills=0.16.8+1.21